# Generated by Django 4.1.6 on 2023-02-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_id_alter_faculty_id_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
