# Generated by Django 4.1.6 on 2023-02-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
